### ISSUE TITLE
Cambiar consulta de noticias

### ISSUE THREAD

**Issue by goinnn** [openwebinars-django/newspaper#2]
Cambiar la consulta:

```
News.objects.filter(
    publish_date__lte=datetime.now()).order_by('publish_date')
```

Por algo como esto:

```
News.objects.published()
```

Usando managers:
https://openwebinars.net/academia/9/curso-de-django/451/managers/

**Comment by jcdero** [comment]
No sabía como se me asignaba la issue, pero ya he añadido un pull request con este cambio.

Saludos.

**Comment by goinnn** [comment]
No estabas añadido a la organización openwebinars-django. Ahora tienes una invitación en tu correo

**Comment by goinnn** [comment]
Cerrado en 853e1c737917f29f54a5a7678d0ec71ffb1db8b4
